# -*- coding: utf8 -*-
# Copyright (c) 2017-2025 Tencent. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



from tencentcloud.common.abstract_client_async import AbstractClient
from tencentcloud.sts.v20180813 import models
from typing import Dict


class StsClient(AbstractClient):
    _apiVersion = '2018-08-13'
    _endpoint = 'sts.intl.tencentcloudapi.com'
    _service = 'sts'

    async def AssumeRole(
            self,
            request: models.AssumeRoleRequest,
            opts: Dict = None,
    ) -> models.AssumeRoleResponse:
        """
        This API is used to request temporary access credentials for assuming a role.

        This API is used to describe the composition of role policies.

        This API is used to specify the role trust policy, which defines who can assume the role.

        This API is used to specify the role permission policy, which defines what actions can be performed after assuming the role.


        This API is used to describe the conditions under which a role can be assumed.

        This API is used to bind a policy that allows a user to call AssumeRole.

        This API is used to add a user as a principal in the role trust policy.
        """
        
        kwargs = {}
        kwargs["action"] = "AssumeRole"
        kwargs["params"] = request._serialize()
        kwargs["resp_cls"] = models.AssumeRoleResponse
        kwargs["headers"] = request.headers
        kwargs["opts"] = opts or {}
        
        return await self.call_and_deserialize(**kwargs)
        
    async def AssumeRoleWithSAML(
            self,
            request: models.AssumeRoleWithSAMLRequest,
            opts: Dict = None,
    ) -> models.AssumeRoleWithSAMLResponse:
        """
        This API is used to request temporary access credentials for a role based on a SAML assertion.

        Note: When called with signature method v3, header `X-TC-Token` could be ignored, and `Authorization` should be SKIP.
        """
        
        kwargs = {}
        kwargs["action"] = "AssumeRoleWithSAML"
        kwargs["params"] = request._serialize()
        kwargs["resp_cls"] = models.AssumeRoleWithSAMLResponse
        kwargs["headers"] = request.headers
        kwargs["opts"] = opts or {}
        
        return await self.call_and_deserialize(**kwargs)
        
    async def AssumeRoleWithWebIdentity(
            self,
            request: models.AssumeRoleWithWebIdentityRequest,
            opts: Dict = None,
    ) -> models.AssumeRoleWithWebIdentityResponse:
        """
        This API is used to apply for an OIDC role credential.

        Note: When called with signature method v3, header `X-TC-Token` could be ignored, and `Authorization` should be SKIP.
        """
        
        kwargs = {}
        kwargs["action"] = "AssumeRoleWithWebIdentity"
        kwargs["params"] = request._serialize()
        kwargs["resp_cls"] = models.AssumeRoleWithWebIdentityResponse
        kwargs["headers"] = request.headers
        kwargs["opts"] = opts or {}
        
        return await self.call_and_deserialize(**kwargs)
        
    async def GetCallerIdentity(
            self,
            request: models.GetCallerIdentityRequest,
            opts: Dict = None,
    ) -> models.GetCallerIdentityResponse:
        """
        This API is used to get the identity information of the current caller.

        This API is used to get the identity information using the persistent keys of the root account and sub-account as well as the temporary credentials generated by AssumeRole and GetFederationToken.
        """
        
        kwargs = {}
        kwargs["action"] = "GetCallerIdentity"
        kwargs["params"] = request._serialize()
        kwargs["resp_cls"] = models.GetCallerIdentityResponse
        kwargs["headers"] = request.headers
        kwargs["opts"] = opts or {}
        
        return await self.call_and_deserialize(**kwargs)
        
    async def GetFederationToken(
            self,
            request: models.GetFederationTokenRequest,
            opts: Dict = None,
    ) -> models.GetFederationTokenResponse:
        """
        This API is used to provide instructions.

        This API is used to return a set of temporary access credentials. A typical application scenario is for proxy applications to centrally request temporary access credentials and distribute them to other distributed terminal applications within the enterprise network, such as terminal applications uploading files to COS. This API only supports calls with permanent keys.

        This API is used to implement best practices.

        1. This API is used to recommend reusing temporary access credentials within their validity period to avoid rate limiting due to increased business request rates.
        2. This API is used to recommend granting temporary access credentials with the principle of least privilege.
        3. This API is used to recommend not using the root account for permanent keys calling the API.
        """
        
        kwargs = {}
        kwargs["action"] = "GetFederationToken"
        kwargs["params"] = request._serialize()
        kwargs["resp_cls"] = models.GetFederationTokenResponse
        kwargs["headers"] = request.headers
        kwargs["opts"] = opts or {}
        
        return await self.call_and_deserialize(**kwargs)