# -*- coding: utf8 -*-
# Copyright (c) 2017-2025 Tencent. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import warnings

from tencentcloud.common.abstract_model import AbstractModel


class DescribeMNGMAUDataDetailRequest(AbstractModel):
    r"""DescribeMNGMAUDataDetail request structure.

    """

    def __init__(self):
        r"""
        :param _DataType: Type
        :type DataType: int
        :param _PlatformId: Tenant ID
        :type PlatformId: str
        :param _ApplicationId: Superapp ID
        :type ApplicationId: str
        :param _MNPId: Mini program appid, required. When provided, the query is performed based on the mini program.
        :type MNPId: str
        :param _MNPTeamId: Mini program team ID
        :type MNPTeamId: int
        """
        self._DataType = None
        self._PlatformId = None
        self._ApplicationId = None
        self._MNPId = None
        self._MNPTeamId = None

    @property
    def DataType(self):
        r"""Type
        :rtype: int
        """
        return self._DataType

    @DataType.setter
    def DataType(self, DataType):
        self._DataType = DataType

    @property
    def PlatformId(self):
        r"""Tenant ID
        :rtype: str
        """
        return self._PlatformId

    @PlatformId.setter
    def PlatformId(self, PlatformId):
        self._PlatformId = PlatformId

    @property
    def ApplicationId(self):
        r"""Superapp ID
        :rtype: str
        """
        return self._ApplicationId

    @ApplicationId.setter
    def ApplicationId(self, ApplicationId):
        self._ApplicationId = ApplicationId

    @property
    def MNPId(self):
        r"""Mini program appid, required. When provided, the query is performed based on the mini program.
        :rtype: str
        """
        return self._MNPId

    @MNPId.setter
    def MNPId(self, MNPId):
        self._MNPId = MNPId

    @property
    def MNPTeamId(self):
        r"""Mini program team ID
        :rtype: int
        """
        return self._MNPTeamId

    @MNPTeamId.setter
    def MNPTeamId(self, MNPTeamId):
        self._MNPTeamId = MNPTeamId


    def _deserialize(self, params):
        self._DataType = params.get("DataType")
        self._PlatformId = params.get("PlatformId")
        self._ApplicationId = params.get("ApplicationId")
        self._MNPId = params.get("MNPId")
        self._MNPTeamId = params.get("MNPTeamId")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class DescribeMNGMAUDataDetailResponse(AbstractModel):
    r"""DescribeMNGMAUDataDetail response structure.

    """

    def __init__(self):
        r"""
        :param _Data: Data display
Note: This field may return null, indicating that no valid values can be obtained.
        :type Data: list of MAUDetail
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""Data display
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: list of MAUDetail
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = []
            for item in params.get("Data"):
                obj = MAUDetail()
                obj._deserialize(item)
                self._Data.append(obj)
        self._RequestId = params.get("RequestId")


class DescribeMNGMAULineChartRequest(AbstractModel):
    r"""DescribeMNGMAULineChart request structure.

    """

    def __init__(self):
        r"""
        :param _DataType: Type: 0 Non-production data, 1 Production data 
        :type DataType: int
        :param _PlatformId: Tenant ID
        :type PlatformId: str
        :param _ApplicationId: Superapp ID
        :type ApplicationId: str
        :param _MNPId: Mini program appid, required. When provided, the query is performed based on the mini program.
        :type MNPId: str
        :param _MNPTeamId: Mini program team ID
        :type MNPTeamId: int
        """
        self._DataType = None
        self._PlatformId = None
        self._ApplicationId = None
        self._MNPId = None
        self._MNPTeamId = None

    @property
    def DataType(self):
        r"""Type: 0 Non-production data, 1 Production data 
        :rtype: int
        """
        return self._DataType

    @DataType.setter
    def DataType(self, DataType):
        self._DataType = DataType

    @property
    def PlatformId(self):
        r"""Tenant ID
        :rtype: str
        """
        return self._PlatformId

    @PlatformId.setter
    def PlatformId(self, PlatformId):
        self._PlatformId = PlatformId

    @property
    def ApplicationId(self):
        r"""Superapp ID
        :rtype: str
        """
        return self._ApplicationId

    @ApplicationId.setter
    def ApplicationId(self, ApplicationId):
        self._ApplicationId = ApplicationId

    @property
    def MNPId(self):
        r"""Mini program appid, required. When provided, the query is performed based on the mini program.
        :rtype: str
        """
        return self._MNPId

    @MNPId.setter
    def MNPId(self, MNPId):
        self._MNPId = MNPId

    @property
    def MNPTeamId(self):
        r"""Mini program team ID
        :rtype: int
        """
        return self._MNPTeamId

    @MNPTeamId.setter
    def MNPTeamId(self, MNPTeamId):
        self._MNPTeamId = MNPTeamId


    def _deserialize(self, params):
        self._DataType = params.get("DataType")
        self._PlatformId = params.get("PlatformId")
        self._ApplicationId = params.get("ApplicationId")
        self._MNPId = params.get("MNPId")
        self._MNPTeamId = params.get("MNPTeamId")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class DescribeMNGMAULineChartResponse(AbstractModel):
    r"""DescribeMNGMAULineChart response structure.

    """

    def __init__(self):
        r"""
        :param _Data: Data display at the top of the page
Note: This field may return null, indicating that no valid values can be obtained.
        :type Data: list of MNGMAULineChartData
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""Data display at the top of the page
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: list of MNGMAULineChartData
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = []
            for item in params.get("Data"):
                obj = MNGMAULineChartData()
                obj._deserialize(item)
                self._Data.append(obj)
        self._RequestId = params.get("RequestId")


class DescribeMNGMAUMonthlyComparisonMetricCardRequest(AbstractModel):
    r"""DescribeMNGMAUMonthlyComparisonMetricCard request structure.

    """

    def __init__(self):
        r"""
        :param _SourceMonth: Start time in YYYYMMDD format
        :type SourceMonth: int
        :param _DataType: Type: 0 Non-production data, 1 Production data 
        :type DataType: int
        :param _PlatformId: Tenant ID
        :type PlatformId: str
        :param _TargetMonth: End time in YYYYMMDD format
        :type TargetMonth: int
        :param _ApplicationId: Superapp ID starting with App
        :type ApplicationId: str
        :param _MNPId: Mini program appid, required. When provided, the query is performed based on the mini program.
        :type MNPId: str
        :param _MNPTeamId: Mini program team ID, required. When provided, the query is performed based on the mini program team.
        :type MNPTeamId: int
        """
        self._SourceMonth = None
        self._DataType = None
        self._PlatformId = None
        self._TargetMonth = None
        self._ApplicationId = None
        self._MNPId = None
        self._MNPTeamId = None

    @property
    def SourceMonth(self):
        r"""Start time in YYYYMMDD format
        :rtype: int
        """
        return self._SourceMonth

    @SourceMonth.setter
    def SourceMonth(self, SourceMonth):
        self._SourceMonth = SourceMonth

    @property
    def DataType(self):
        r"""Type: 0 Non-production data, 1 Production data 
        :rtype: int
        """
        return self._DataType

    @DataType.setter
    def DataType(self, DataType):
        self._DataType = DataType

    @property
    def PlatformId(self):
        r"""Tenant ID
        :rtype: str
        """
        return self._PlatformId

    @PlatformId.setter
    def PlatformId(self, PlatformId):
        self._PlatformId = PlatformId

    @property
    def TargetMonth(self):
        r"""End time in YYYYMMDD format
        :rtype: int
        """
        return self._TargetMonth

    @TargetMonth.setter
    def TargetMonth(self, TargetMonth):
        self._TargetMonth = TargetMonth

    @property
    def ApplicationId(self):
        r"""Superapp ID starting with App
        :rtype: str
        """
        return self._ApplicationId

    @ApplicationId.setter
    def ApplicationId(self, ApplicationId):
        self._ApplicationId = ApplicationId

    @property
    def MNPId(self):
        r"""Mini program appid, required. When provided, the query is performed based on the mini program.
        :rtype: str
        """
        return self._MNPId

    @MNPId.setter
    def MNPId(self, MNPId):
        self._MNPId = MNPId

    @property
    def MNPTeamId(self):
        r"""Mini program team ID, required. When provided, the query is performed based on the mini program team.
        :rtype: int
        """
        return self._MNPTeamId

    @MNPTeamId.setter
    def MNPTeamId(self, MNPTeamId):
        self._MNPTeamId = MNPTeamId


    def _deserialize(self, params):
        self._SourceMonth = params.get("SourceMonth")
        self._DataType = params.get("DataType")
        self._PlatformId = params.get("PlatformId")
        self._TargetMonth = params.get("TargetMonth")
        self._ApplicationId = params.get("ApplicationId")
        self._MNPId = params.get("MNPId")
        self._MNPTeamId = params.get("MNPTeamId")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class DescribeMNGMAUMonthlyComparisonMetricCardResponse(AbstractModel):
    r"""DescribeMNGMAUMonthlyComparisonMetricCard response structure.

    """

    def __init__(self):
        r"""
        :param _Data: Data display at the top of the page
        :type Data: :class:`tencentcloud.tcsas.v20250106.models.MAUIndicatorCard`
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""Data display at the top of the page
        :rtype: :class:`tencentcloud.tcsas.v20250106.models.MAUIndicatorCard`
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = MAUIndicatorCard()
            self._Data._deserialize(params.get("Data"))
        self._RequestId = params.get("RequestId")


class DescribeMNPMAUDataDetailRequest(AbstractModel):
    r"""DescribeMNPMAUDataDetail request structure.

    """

    def __init__(self):
        r"""
        :param _DataType: Type: 0 Non-production data, 1 Production data
        :type DataType: int
        :param _PlatformId: Tenant ID
        :type PlatformId: str
        :param _ApplicationId: Superapp ID
        :type ApplicationId: str
        :param _MNPId: Mini program appid, required. When provided, the query is performed based on the mini program.
        :type MNPId: str
        :param _MNPTeamId: Program team ID, -1 means not provided
        :type MNPTeamId: int
        """
        self._DataType = None
        self._PlatformId = None
        self._ApplicationId = None
        self._MNPId = None
        self._MNPTeamId = None

    @property
    def DataType(self):
        r"""Type: 0 Non-production data, 1 Production data
        :rtype: int
        """
        return self._DataType

    @DataType.setter
    def DataType(self, DataType):
        self._DataType = DataType

    @property
    def PlatformId(self):
        r"""Tenant ID
        :rtype: str
        """
        return self._PlatformId

    @PlatformId.setter
    def PlatformId(self, PlatformId):
        self._PlatformId = PlatformId

    @property
    def ApplicationId(self):
        r"""Superapp ID
        :rtype: str
        """
        return self._ApplicationId

    @ApplicationId.setter
    def ApplicationId(self, ApplicationId):
        self._ApplicationId = ApplicationId

    @property
    def MNPId(self):
        r"""Mini program appid, required. When provided, the query is performed based on the mini program.
        :rtype: str
        """
        return self._MNPId

    @MNPId.setter
    def MNPId(self, MNPId):
        self._MNPId = MNPId

    @property
    def MNPTeamId(self):
        r"""Program team ID, -1 means not provided
        :rtype: int
        """
        return self._MNPTeamId

    @MNPTeamId.setter
    def MNPTeamId(self, MNPTeamId):
        self._MNPTeamId = MNPTeamId


    def _deserialize(self, params):
        self._DataType = params.get("DataType")
        self._PlatformId = params.get("PlatformId")
        self._ApplicationId = params.get("ApplicationId")
        self._MNPId = params.get("MNPId")
        self._MNPTeamId = params.get("MNPTeamId")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class DescribeMNPMAUDataDetailResponse(AbstractModel):
    r"""DescribeMNPMAUDataDetail response structure.

    """

    def __init__(self):
        r"""
        :param _Data: Data display
Note: This field may return null, indicating that no valid values can be obtained.
        :type Data: list of MAUDetail
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""Data display
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: list of MAUDetail
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = []
            for item in params.get("Data"):
                obj = MAUDetail()
                obj._deserialize(item)
                self._Data.append(obj)
        self._RequestId = params.get("RequestId")


class DescribeMNPMAULineChartRequest(AbstractModel):
    r"""DescribeMNPMAULineChart request structure.

    """

    def __init__(self):
        r"""
        :param _DataType: Type: 0 Non-production data, 1 Production data
        :type DataType: int
        :param _PlatformId: Tenant ID
        :type PlatformId: str
        :param _ApplicationId: Superapp ID
        :type ApplicationId: str
        :param _MNPId: Mini program appid, required. When provided, the query is performed based on the mini program.
        :type MNPId: str
        :param _MNPTeamId: Mini program team ID
        :type MNPTeamId: int
        """
        self._DataType = None
        self._PlatformId = None
        self._ApplicationId = None
        self._MNPId = None
        self._MNPTeamId = None

    @property
    def DataType(self):
        r"""Type: 0 Non-production data, 1 Production data
        :rtype: int
        """
        return self._DataType

    @DataType.setter
    def DataType(self, DataType):
        self._DataType = DataType

    @property
    def PlatformId(self):
        r"""Tenant ID
        :rtype: str
        """
        return self._PlatformId

    @PlatformId.setter
    def PlatformId(self, PlatformId):
        self._PlatformId = PlatformId

    @property
    def ApplicationId(self):
        r"""Superapp ID
        :rtype: str
        """
        return self._ApplicationId

    @ApplicationId.setter
    def ApplicationId(self, ApplicationId):
        self._ApplicationId = ApplicationId

    @property
    def MNPId(self):
        r"""Mini program appid, required. When provided, the query is performed based on the mini program.
        :rtype: str
        """
        return self._MNPId

    @MNPId.setter
    def MNPId(self, MNPId):
        self._MNPId = MNPId

    @property
    def MNPTeamId(self):
        r"""Mini program team ID
        :rtype: int
        """
        return self._MNPTeamId

    @MNPTeamId.setter
    def MNPTeamId(self, MNPTeamId):
        self._MNPTeamId = MNPTeamId


    def _deserialize(self, params):
        self._DataType = params.get("DataType")
        self._PlatformId = params.get("PlatformId")
        self._ApplicationId = params.get("ApplicationId")
        self._MNPId = params.get("MNPId")
        self._MNPTeamId = params.get("MNPTeamId")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class DescribeMNPMAULineChartResponse(AbstractModel):
    r"""DescribeMNPMAULineChart response structure.

    """

    def __init__(self):
        r"""
        :param _Data: Data display
Note: This field may return null, indicating that no valid values can be obtained.
        :type Data: list of MAUChartData
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""Data display
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: list of MAUChartData
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = []
            for item in params.get("Data"):
                obj = MAUChartData()
                obj._deserialize(item)
                self._Data.append(obj)
        self._RequestId = params.get("RequestId")


class DescribeMNPMAUMetricCardRequest(AbstractModel):
    r"""DescribeMNPMAUMetricCard request structure.

    """

    def __init__(self):
        r"""
        :param _SourceMonth: Start time in YYYYMMDD format
        :type SourceMonth: int
        :param _DataType: Type: 0 Non-production data, 1 Production data 
        :type DataType: int
        :param _PlatformId: Tenant ID
        :type PlatformId: str
        :param _TargetMonth: End time in YYYYMMDD format
        :type TargetMonth: int
        :param _ApplicationId: Superapp ID starting with App
        :type ApplicationId: str
        :param _MNPId: Mini program appid, required. When provided, the query is performed based on the mini program.
        :type MNPId: str
        :param _MNPTeamId: Mini program team ID, required. When provided, the query is performed based on the mini program team.
        :type MNPTeamId: int
        """
        self._SourceMonth = None
        self._DataType = None
        self._PlatformId = None
        self._TargetMonth = None
        self._ApplicationId = None
        self._MNPId = None
        self._MNPTeamId = None

    @property
    def SourceMonth(self):
        r"""Start time in YYYYMMDD format
        :rtype: int
        """
        return self._SourceMonth

    @SourceMonth.setter
    def SourceMonth(self, SourceMonth):
        self._SourceMonth = SourceMonth

    @property
    def DataType(self):
        r"""Type: 0 Non-production data, 1 Production data 
        :rtype: int
        """
        return self._DataType

    @DataType.setter
    def DataType(self, DataType):
        self._DataType = DataType

    @property
    def PlatformId(self):
        r"""Tenant ID
        :rtype: str
        """
        return self._PlatformId

    @PlatformId.setter
    def PlatformId(self, PlatformId):
        self._PlatformId = PlatformId

    @property
    def TargetMonth(self):
        r"""End time in YYYYMMDD format
        :rtype: int
        """
        return self._TargetMonth

    @TargetMonth.setter
    def TargetMonth(self, TargetMonth):
        self._TargetMonth = TargetMonth

    @property
    def ApplicationId(self):
        r"""Superapp ID starting with App
        :rtype: str
        """
        return self._ApplicationId

    @ApplicationId.setter
    def ApplicationId(self, ApplicationId):
        self._ApplicationId = ApplicationId

    @property
    def MNPId(self):
        r"""Mini program appid, required. When provided, the query is performed based on the mini program.
        :rtype: str
        """
        return self._MNPId

    @MNPId.setter
    def MNPId(self, MNPId):
        self._MNPId = MNPId

    @property
    def MNPTeamId(self):
        r"""Mini program team ID, required. When provided, the query is performed based on the mini program team.
        :rtype: int
        """
        return self._MNPTeamId

    @MNPTeamId.setter
    def MNPTeamId(self, MNPTeamId):
        self._MNPTeamId = MNPTeamId


    def _deserialize(self, params):
        self._SourceMonth = params.get("SourceMonth")
        self._DataType = params.get("DataType")
        self._PlatformId = params.get("PlatformId")
        self._TargetMonth = params.get("TargetMonth")
        self._ApplicationId = params.get("ApplicationId")
        self._MNPId = params.get("MNPId")
        self._MNPTeamId = params.get("MNPTeamId")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class DescribeMNPMAUMetricCardResponse(AbstractModel):
    r"""DescribeMNPMAUMetricCard response structure.

    """

    def __init__(self):
        r"""
        :param _Data: Data display at the top of the page
        :type Data: :class:`tencentcloud.tcsas.v20250106.models.MAUIndicatorCard`
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""Data display at the top of the page
        :rtype: :class:`tencentcloud.tcsas.v20250106.models.MAUIndicatorCard`
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = MAUIndicatorCard()
            self._Data._deserialize(params.get("Data"))
        self._RequestId = params.get("RequestId")


class MAUChartData(AbstractModel):
    r"""MAU line chart data

    """

    def __init__(self):
        r"""
        :param _DataTime: Year and month: 2024-12
        :type DataTime: int
        :param _MAUCount: Value
        :type MAUCount: int
        :param _UpdateTime: Data update time, only available when MAUCount is greater than 0.
        :type UpdateTime: int
        """
        self._DataTime = None
        self._MAUCount = None
        self._UpdateTime = None

    @property
    def DataTime(self):
        r"""Year and month: 2024-12
        :rtype: int
        """
        return self._DataTime

    @DataTime.setter
    def DataTime(self, DataTime):
        self._DataTime = DataTime

    @property
    def MAUCount(self):
        r"""Value
        :rtype: int
        """
        return self._MAUCount

    @MAUCount.setter
    def MAUCount(self, MAUCount):
        self._MAUCount = MAUCount

    @property
    def UpdateTime(self):
        r"""Data update time, only available when MAUCount is greater than 0.
        :rtype: int
        """
        return self._UpdateTime

    @UpdateTime.setter
    def UpdateTime(self, UpdateTime):
        self._UpdateTime = UpdateTime


    def _deserialize(self, params):
        self._DataTime = params.get("DataTime")
        self._MAUCount = params.get("MAUCount")
        self._UpdateTime = params.get("UpdateTime")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class MAUDetail(AbstractModel):
    r"""Mini program MAU details

    """

    def __init__(self):
        r"""
        :param _MNPName: Mini program name
        :type MNPName: str
        :param _DataList: MAU details
        :type DataList: list of MAULineChartData
        """
        self._MNPName = None
        self._DataList = None

    @property
    def MNPName(self):
        r"""Mini program name
        :rtype: str
        """
        return self._MNPName

    @MNPName.setter
    def MNPName(self, MNPName):
        self._MNPName = MNPName

    @property
    def DataList(self):
        r"""MAU details
        :rtype: list of MAULineChartData
        """
        return self._DataList

    @DataList.setter
    def DataList(self, DataList):
        self._DataList = DataList


    def _deserialize(self, params):
        self._MNPName = params.get("MNPName")
        if params.get("DataList") is not None:
            self._DataList = []
            for item in params.get("DataList"):
                obj = MAULineChartData()
                obj._deserialize(item)
                self._DataList.append(obj)
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class MAUIndicatorCard(AbstractModel):
    r"""MAU metric comparison response data

    """

    def __init__(self):
        r"""
        :param _ComparisonRatio: Growth rate (targetData - sourceData) / sourceData, returns 0 when SourceMAUNum is 0
        :type ComparisonRatio: str
        :param _ComparisonResult: 1 Increase
2 Decrease
Returns 0 when SourceMAUNum is 0
        :type ComparisonResult: int
        :param _SourceMAUNum: Last month's MAU data
        :type SourceMAUNum: int
        :param _TargetMAUNum: This month's MAU data
        :type TargetMAUNum: int
        :param _FlushTime: Data timestamp
        :type FlushTime: int
        """
        self._ComparisonRatio = None
        self._ComparisonResult = None
        self._SourceMAUNum = None
        self._TargetMAUNum = None
        self._FlushTime = None

    @property
    def ComparisonRatio(self):
        r"""Growth rate (targetData - sourceData) / sourceData, returns 0 when SourceMAUNum is 0
        :rtype: str
        """
        return self._ComparisonRatio

    @ComparisonRatio.setter
    def ComparisonRatio(self, ComparisonRatio):
        self._ComparisonRatio = ComparisonRatio

    @property
    def ComparisonResult(self):
        r"""1 Increase
2 Decrease
Returns 0 when SourceMAUNum is 0
        :rtype: int
        """
        return self._ComparisonResult

    @ComparisonResult.setter
    def ComparisonResult(self, ComparisonResult):
        self._ComparisonResult = ComparisonResult

    @property
    def SourceMAUNum(self):
        r"""Last month's MAU data
        :rtype: int
        """
        return self._SourceMAUNum

    @SourceMAUNum.setter
    def SourceMAUNum(self, SourceMAUNum):
        self._SourceMAUNum = SourceMAUNum

    @property
    def TargetMAUNum(self):
        r"""This month's MAU data
        :rtype: int
        """
        return self._TargetMAUNum

    @TargetMAUNum.setter
    def TargetMAUNum(self, TargetMAUNum):
        self._TargetMAUNum = TargetMAUNum

    @property
    def FlushTime(self):
        r"""Data timestamp
        :rtype: int
        """
        return self._FlushTime

    @FlushTime.setter
    def FlushTime(self, FlushTime):
        self._FlushTime = FlushTime


    def _deserialize(self, params):
        self._ComparisonRatio = params.get("ComparisonRatio")
        self._ComparisonResult = params.get("ComparisonResult")
        self._SourceMAUNum = params.get("SourceMAUNum")
        self._TargetMAUNum = params.get("TargetMAUNum")
        self._FlushTime = params.get("FlushTime")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class MAULineChartData(AbstractModel):
    r"""Line chart data

    """

    def __init__(self):
        r"""
        :param _DataTime: Year-month date data
Note: This field may return null, indicating that no valid values can be obtained.
        :type DataTime: int
        :param _MAUCount: MAU data
Note: This field may return null, indicating that no valid values can be obtained.
        :type MAUCount: str
        """
        self._DataTime = None
        self._MAUCount = None

    @property
    def DataTime(self):
        r"""Year-month date data
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: int
        """
        return self._DataTime

    @DataTime.setter
    def DataTime(self, DataTime):
        self._DataTime = DataTime

    @property
    def MAUCount(self):
        r"""MAU data
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: str
        """
        return self._MAUCount

    @MAUCount.setter
    def MAUCount(self, MAUCount):
        self._MAUCount = MAUCount


    def _deserialize(self, params):
        self._DataTime = params.get("DataTime")
        self._MAUCount = params.get("MAUCount")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class MNGMAULineChartData(AbstractModel):
    r"""Mini game MAU line chart data

    """

    def __init__(self):
        r"""
        :param _DataTime: Year-month-date data
Note: This field may return null, indicating that no valid values can be obtained.
        :type DataTime: int
        :param _MAUCount: MAU data
Note: This field may return null, indicating that no valid values can be obtained.
        :type MAUCount: int
        :param _UpdateTime: Update time
        :type UpdateTime: int
        """
        self._DataTime = None
        self._MAUCount = None
        self._UpdateTime = None

    @property
    def DataTime(self):
        r"""Year-month-date data
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: int
        """
        return self._DataTime

    @DataTime.setter
    def DataTime(self, DataTime):
        self._DataTime = DataTime

    @property
    def MAUCount(self):
        r"""MAU data
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: int
        """
        return self._MAUCount

    @MAUCount.setter
    def MAUCount(self, MAUCount):
        self._MAUCount = MAUCount

    @property
    def UpdateTime(self):
        r"""Update time
        :rtype: int
        """
        return self._UpdateTime

    @UpdateTime.setter
    def UpdateTime(self, UpdateTime):
        self._UpdateTime = UpdateTime


    def _deserialize(self, params):
        self._DataTime = params.get("DataTime")
        self._MAUCount = params.get("MAUCount")
        self._UpdateTime = params.get("UpdateTime")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        