# -*- coding: utf8 -*-
# Copyright (c) 2017-2025 Tencent. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import warnings

from tencentcloud.common.abstract_model import AbstractModel


class AssessDeviceRiskPremiumProRequest(AbstractModel):
    r"""AssessDeviceRiskPremiumPro request structure.

    """

    def __init__(self):
        r"""
        :param _DeviceToken: <p>Device fingerprint token, obtained after integration of the device fingerprint SDK into your website or application</p>
        :type DeviceToken: str
        :param _UserIp: <p>User client IP address(IPv4 or IPv6)</p>
        :type UserIp: str
        """
        self._DeviceToken = None
        self._UserIp = None

    @property
    def DeviceToken(self):
        r"""<p>Device fingerprint token, obtained after integration of the device fingerprint SDK into your website or application</p>
        :rtype: str
        """
        return self._DeviceToken

    @DeviceToken.setter
    def DeviceToken(self, DeviceToken):
        self._DeviceToken = DeviceToken

    @property
    def UserIp(self):
        r"""<p>User client IP address(IPv4 or IPv6)</p>
        :rtype: str
        """
        return self._UserIp

    @UserIp.setter
    def UserIp(self, UserIp):
        self._UserIp = UserIp


    def _deserialize(self, params):
        self._DeviceToken = params.get("DeviceToken")
        self._UserIp = params.get("UserIp")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class AssessDeviceRiskPremiumProResponse(AbstractModel):
    r"""AssessDeviceRiskPremiumPro response structure.

    """

    def __init__(self):
        r"""
        :param _Data: <p>The results of AssessDeviceRiskPremiumPro</p>
        :type Data: :class:`tencentcloud.rce.v20260130.models.AssessDeviceRiskPremiumRsp`
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""<p>The results of AssessDeviceRiskPremiumPro</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.AssessDeviceRiskPremiumRsp`
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = AssessDeviceRiskPremiumRsp()
            self._Data._deserialize(params.get("Data"))
        self._RequestId = params.get("RequestId")


class AssessDeviceRiskPremiumRsp(AbstractModel):
    r"""The results of AssessDeviceRiskPremiumPro

    """

    def __init__(self):
        r"""
        :param _Decision: <p>Decision information</p>
        :type Decision: :class:`tencentcloud.rce.v20260130.models.Decision`
        :param _Score: <p>The risk score information of the device</p>
        :type Score: :class:`tencentcloud.rce.v20260130.models.DataScore`
        :param _Device: <p>The basic information of the device</p>
        :type Device: :class:`tencentcloud.rce.v20260130.models.Device`
        :param _Environment: <p>Basic IP environment information</p>
Note: This field may return null, indicating that no valid values can be obtained.
        :type Environment: :class:`tencentcloud.rce.v20260130.models.Environment`
        """
        self._Decision = None
        self._Score = None
        self._Device = None
        self._Environment = None

    @property
    def Decision(self):
        r"""<p>Decision information</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.Decision`
        """
        return self._Decision

    @Decision.setter
    def Decision(self, Decision):
        self._Decision = Decision

    @property
    def Score(self):
        r"""<p>The risk score information of the device</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.DataScore`
        """
        return self._Score

    @Score.setter
    def Score(self, Score):
        self._Score = Score

    @property
    def Device(self):
        r"""<p>The basic information of the device</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.Device`
        """
        return self._Device

    @Device.setter
    def Device(self, Device):
        self._Device = Device

    @property
    def Environment(self):
        r"""<p>Basic IP environment information</p>
Note: This field may return null, indicating that no valid values can be obtained.
        :rtype: :class:`tencentcloud.rce.v20260130.models.Environment`
        """
        return self._Environment

    @Environment.setter
    def Environment(self, Environment):
        self._Environment = Environment


    def _deserialize(self, params):
        if params.get("Decision") is not None:
            self._Decision = Decision()
            self._Decision._deserialize(params.get("Decision"))
        if params.get("Score") is not None:
            self._Score = DataScore()
            self._Score._deserialize(params.get("Score"))
        if params.get("Device") is not None:
            self._Device = Device()
            self._Device._deserialize(params.get("Device"))
        if params.get("Environment") is not None:
            self._Environment = Environment()
            self._Environment._deserialize(params.get("Environment"))
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class AssessDeviceRiskProRequest(AbstractModel):
    r"""AssessDeviceRiskPro request structure.

    """

    def __init__(self):
        r"""
        :param _DeviceToken: <p>Device fingerprint token, obtained after integration of the device fingerprint SDK into your website or application</p>
        :type DeviceToken: str
        :param _UserIp: <p>User client IP address(IPv4 or IPv6)</p>
        :type UserIp: str
        """
        self._DeviceToken = None
        self._UserIp = None

    @property
    def DeviceToken(self):
        r"""<p>Device fingerprint token, obtained after integration of the device fingerprint SDK into your website or application</p>
        :rtype: str
        """
        return self._DeviceToken

    @DeviceToken.setter
    def DeviceToken(self, DeviceToken):
        self._DeviceToken = DeviceToken

    @property
    def UserIp(self):
        r"""<p>User client IP address(IPv4 or IPv6)</p>
        :rtype: str
        """
        return self._UserIp

    @UserIp.setter
    def UserIp(self, UserIp):
        self._UserIp = UserIp


    def _deserialize(self, params):
        self._DeviceToken = params.get("DeviceToken")
        self._UserIp = params.get("UserIp")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class AssessDeviceRiskProResponse(AbstractModel):
    r"""AssessDeviceRiskPro response structure.

    """

    def __init__(self):
        r"""
        :param _Data: <p>The results of AssessDeviceRiskPro</p>
        :type Data: :class:`tencentcloud.rce.v20260130.models.AssessDeviceRiskRsp`
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""<p>The results of AssessDeviceRiskPro</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.AssessDeviceRiskRsp`
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = AssessDeviceRiskRsp()
            self._Data._deserialize(params.get("Data"))
        self._RequestId = params.get("RequestId")


class AssessDeviceRiskRsp(AbstractModel):
    r"""The results of AssessDeviceRiskPro

    """

    def __init__(self):
        r"""
        :param _Score: <p>The risk score information of the device</p>
        :type Score: :class:`tencentcloud.rce.v20260130.models.DataScore`
        :param _Device: <p>The basic information of the device</p>
        :type Device: :class:`tencentcloud.rce.v20260130.models.Device`
        """
        self._Score = None
        self._Device = None

    @property
    def Score(self):
        r"""<p>The risk score information of the device</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.DataScore`
        """
        return self._Score

    @Score.setter
    def Score(self, Score):
        self._Score = Score

    @property
    def Device(self):
        r"""<p>The basic information of the device</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.Device`
        """
        return self._Device

    @Device.setter
    def Device(self, Device):
        self._Device = Device


    def _deserialize(self, params):
        if params.get("Score") is not None:
            self._Score = DataScore()
            self._Score._deserialize(params.get("Score"))
        if params.get("Device") is not None:
            self._Device = Device()
            self._Device._deserialize(params.get("Device"))
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class AssessEnvironmentRiskRequest(AbstractModel):
    r"""AssessEnvironmentRisk request structure.

    """

    def __init__(self):
        r"""
        :param _UserIp: <p>User client IP address(IPv4 or IPv6)</p>
        :type UserIp: str
        """
        self._UserIp = None

    @property
    def UserIp(self):
        r"""<p>User client IP address(IPv4 or IPv6)</p>
        :rtype: str
        """
        return self._UserIp

    @UserIp.setter
    def UserIp(self, UserIp):
        self._UserIp = UserIp


    def _deserialize(self, params):
        self._UserIp = params.get("UserIp")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class AssessEnvironmentRiskResponse(AbstractModel):
    r"""AssessEnvironmentRisk response structure.

    """

    def __init__(self):
        r"""
        :param _Data: <p>The results of AssessEnvironmentRisk</p>
        :type Data: :class:`tencentcloud.rce.v20260130.models.AssessEnvironmentRiskRsp`
        :param _RequestId: The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :type RequestId: str
        """
        self._Data = None
        self._RequestId = None

    @property
    def Data(self):
        r"""<p>The results of AssessEnvironmentRisk</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.AssessEnvironmentRiskRsp`
        """
        return self._Data

    @Data.setter
    def Data(self, Data):
        self._Data = Data

    @property
    def RequestId(self):
        r"""The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        :rtype: str
        """
        return self._RequestId

    @RequestId.setter
    def RequestId(self, RequestId):
        self._RequestId = RequestId


    def _deserialize(self, params):
        if params.get("Data") is not None:
            self._Data = AssessEnvironmentRiskRsp()
            self._Data._deserialize(params.get("Data"))
        self._RequestId = params.get("RequestId")


class AssessEnvironmentRiskRsp(AbstractModel):
    r"""The results of AssessEnvironmentRisk

    """

    def __init__(self):
        r"""
        :param _Score: <p>The risk score information of the IP environment</p>
        :type Score: :class:`tencentcloud.rce.v20260130.models.DataScore`
        :param _Environment: <p>The basic information of the IP environment</p>
        :type Environment: :class:`tencentcloud.rce.v20260130.models.Environment`
        """
        self._Score = None
        self._Environment = None

    @property
    def Score(self):
        r"""<p>The risk score information of the IP environment</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.DataScore`
        """
        return self._Score

    @Score.setter
    def Score(self, Score):
        self._Score = Score

    @property
    def Environment(self):
        r"""<p>The basic information of the IP environment</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.Environment`
        """
        return self._Environment

    @Environment.setter
    def Environment(self, Environment):
        self._Environment = Environment


    def _deserialize(self, params):
        if params.get("Score") is not None:
            self._Score = DataScore()
            self._Score._deserialize(params.get("Score"))
        if params.get("Environment") is not None:
            self._Environment = Environment()
            self._Environment._deserialize(params.get("Environment"))
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class DataScore(AbstractModel):
    r"""Risk score information

    """

    def __init__(self):
        r"""
        :param _RiskLevel: <p>Risk level</p>
        :type RiskLevel: int
        :param _RiskLabels: <p>Risk label</p>
        :type RiskLabels: list of RiskLabel
        """
        self._RiskLevel = None
        self._RiskLabels = None

    @property
    def RiskLevel(self):
        r"""<p>Risk level</p>
        :rtype: int
        """
        return self._RiskLevel

    @RiskLevel.setter
    def RiskLevel(self, RiskLevel):
        self._RiskLevel = RiskLevel

    @property
    def RiskLabels(self):
        r"""<p>Risk label</p>
        :rtype: list of RiskLabel
        """
        return self._RiskLabels

    @RiskLabels.setter
    def RiskLabels(self, RiskLabels):
        self._RiskLabels = RiskLabels


    def _deserialize(self, params):
        self._RiskLevel = params.get("RiskLevel")
        if params.get("RiskLabels") is not None:
            self._RiskLabels = []
            for item in params.get("RiskLabels"):
                obj = RiskLabel()
                obj._deserialize(item)
                self._RiskLabels.append(obj)
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class Decision(AbstractModel):
    r"""Decision information

    """

    def __init__(self):
        r"""
        :param _DecisionResult: <p>Decision result</p><ul><li>pass: Pass</li><li>review: Review</li><li>reject: Reject</li></ul>
        :type DecisionResult: str
        """
        self._DecisionResult = None

    @property
    def DecisionResult(self):
        r"""<p>Decision result</p><ul><li>pass: Pass</li><li>review: Review</li><li>reject: Reject</li></ul>
        :rtype: str
        """
        return self._DecisionResult

    @DecisionResult.setter
    def DecisionResult(self, DecisionResult):
        self._DecisionResult = DecisionResult


    def _deserialize(self, params):
        self._DecisionResult = params.get("DecisionResult")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class Device(AbstractModel):
    r"""The basic infomation of the device

    """

    def __init__(self):
        r"""
        :param _DeviceId: <p>The unique id of device returned by RCE</p>
        :type DeviceId: str
        :param _AppVersion: <p>The version of the application</p>
        :type AppVersion: str
        :param _Brand: <p>Device brand</p>
        :type Brand: str
        :param _ClientIp: <p>Client IP address</p>
        :type ClientIp: str
        :param _Model: <p>Device model</p>
        :type Model: str
        :param _NetworkType: <p>Network type of the device</p>
        :type NetworkType: str
        :param _PackageName: <p>The package name of the application</p>
        :type PackageName: str
        :param _Platform: <p>Device platform</p><p>Enumeration value:</p><ul><li>2: Android</li><li>3: IOS</li><li>4: H5</li><li>5: WeChat Mini Program</li></ul>
        :type Platform: str
        :param _SystemVersion: <p>Device system version</p>
        :type SystemVersion: str
        :param _SdkBuildVersion: <p>The build version of SDK</p>
        :type SdkBuildVersion: str
        """
        self._DeviceId = None
        self._AppVersion = None
        self._Brand = None
        self._ClientIp = None
        self._Model = None
        self._NetworkType = None
        self._PackageName = None
        self._Platform = None
        self._SystemVersion = None
        self._SdkBuildVersion = None

    @property
    def DeviceId(self):
        r"""<p>The unique id of device returned by RCE</p>
        :rtype: str
        """
        return self._DeviceId

    @DeviceId.setter
    def DeviceId(self, DeviceId):
        self._DeviceId = DeviceId

    @property
    def AppVersion(self):
        r"""<p>The version of the application</p>
        :rtype: str
        """
        return self._AppVersion

    @AppVersion.setter
    def AppVersion(self, AppVersion):
        self._AppVersion = AppVersion

    @property
    def Brand(self):
        r"""<p>Device brand</p>
        :rtype: str
        """
        return self._Brand

    @Brand.setter
    def Brand(self, Brand):
        self._Brand = Brand

    @property
    def ClientIp(self):
        r"""<p>Client IP address</p>
        :rtype: str
        """
        return self._ClientIp

    @ClientIp.setter
    def ClientIp(self, ClientIp):
        self._ClientIp = ClientIp

    @property
    def Model(self):
        r"""<p>Device model</p>
        :rtype: str
        """
        return self._Model

    @Model.setter
    def Model(self, Model):
        self._Model = Model

    @property
    def NetworkType(self):
        r"""<p>Network type of the device</p>
        :rtype: str
        """
        return self._NetworkType

    @NetworkType.setter
    def NetworkType(self, NetworkType):
        self._NetworkType = NetworkType

    @property
    def PackageName(self):
        r"""<p>The package name of the application</p>
        :rtype: str
        """
        return self._PackageName

    @PackageName.setter
    def PackageName(self, PackageName):
        self._PackageName = PackageName

    @property
    def Platform(self):
        r"""<p>Device platform</p><p>Enumeration value:</p><ul><li>2: Android</li><li>3: IOS</li><li>4: H5</li><li>5: WeChat Mini Program</li></ul>
        :rtype: str
        """
        return self._Platform

    @Platform.setter
    def Platform(self, Platform):
        self._Platform = Platform

    @property
    def SystemVersion(self):
        r"""<p>Device system version</p>
        :rtype: str
        """
        return self._SystemVersion

    @SystemVersion.setter
    def SystemVersion(self, SystemVersion):
        self._SystemVersion = SystemVersion

    @property
    def SdkBuildVersion(self):
        r"""<p>The build version of SDK</p>
        :rtype: str
        """
        return self._SdkBuildVersion

    @SdkBuildVersion.setter
    def SdkBuildVersion(self, SdkBuildVersion):
        self._SdkBuildVersion = SdkBuildVersion


    def _deserialize(self, params):
        self._DeviceId = params.get("DeviceId")
        self._AppVersion = params.get("AppVersion")
        self._Brand = params.get("Brand")
        self._ClientIp = params.get("ClientIp")
        self._Model = params.get("Model")
        self._NetworkType = params.get("NetworkType")
        self._PackageName = params.get("PackageName")
        self._Platform = params.get("Platform")
        self._SystemVersion = params.get("SystemVersion")
        self._SdkBuildVersion = params.get("SdkBuildVersion")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class Environment(AbstractModel):
    r"""The basic information of the IP environment

    """

    def __init__(self):
        r"""
        :param _Location: <p>The geographical location of the IP address</p>
        :type Location: :class:`tencentcloud.rce.v20260130.models.IPLocation`
        :param _Network: <p>The basic IP network information</p>
        :type Network: :class:`tencentcloud.rce.v20260130.models.IPNetwork`
        """
        self._Location = None
        self._Network = None

    @property
    def Location(self):
        r"""<p>The geographical location of the IP address</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.IPLocation`
        """
        return self._Location

    @Location.setter
    def Location(self, Location):
        self._Location = Location

    @property
    def Network(self):
        r"""<p>The basic IP network information</p>
        :rtype: :class:`tencentcloud.rce.v20260130.models.IPNetwork`
        """
        return self._Network

    @Network.setter
    def Network(self, Network):
        self._Network = Network


    def _deserialize(self, params):
        if params.get("Location") is not None:
            self._Location = IPLocation()
            self._Location._deserialize(params.get("Location"))
        if params.get("Network") is not None:
            self._Network = IPNetwork()
            self._Network._deserialize(params.get("Network"))
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class IPLocation(AbstractModel):
    r"""The geographical location of the IP address

    """

    def __init__(self):
        r"""
        :param _Country: <p>The country of the IP address</p>
        :type Country: str
        :param _Region: <p>The region of the IP address</p>
        :type Region: str
        :param _City: <p>The city of the IP address</p>
        :type City: str
        :param _District: <p>The district of the IP address</p>
        :type District: str
        :param _Longitude: <p>The longitude of the IP address</p>
        :type Longitude: str
        :param _Latitude: <p>The latitude of the IP address</p>
        :type Latitude: str
        :param _Timezone: <p>The timezone of the IP address</p>
        :type Timezone: str
        :param _ZipCode: <p>The zip code of the IP address</p>
        :type ZipCode: str
        """
        self._Country = None
        self._Region = None
        self._City = None
        self._District = None
        self._Longitude = None
        self._Latitude = None
        self._Timezone = None
        self._ZipCode = None

    @property
    def Country(self):
        r"""<p>The country of the IP address</p>
        :rtype: str
        """
        return self._Country

    @Country.setter
    def Country(self, Country):
        self._Country = Country

    @property
    def Region(self):
        r"""<p>The region of the IP address</p>
        :rtype: str
        """
        return self._Region

    @Region.setter
    def Region(self, Region):
        self._Region = Region

    @property
    def City(self):
        r"""<p>The city of the IP address</p>
        :rtype: str
        """
        return self._City

    @City.setter
    def City(self, City):
        self._City = City

    @property
    def District(self):
        r"""<p>The district of the IP address</p>
        :rtype: str
        """
        return self._District

    @District.setter
    def District(self, District):
        self._District = District

    @property
    def Longitude(self):
        r"""<p>The longitude of the IP address</p>
        :rtype: str
        """
        return self._Longitude

    @Longitude.setter
    def Longitude(self, Longitude):
        self._Longitude = Longitude

    @property
    def Latitude(self):
        r"""<p>The latitude of the IP address</p>
        :rtype: str
        """
        return self._Latitude

    @Latitude.setter
    def Latitude(self, Latitude):
        self._Latitude = Latitude

    @property
    def Timezone(self):
        r"""<p>The timezone of the IP address</p>
        :rtype: str
        """
        return self._Timezone

    @Timezone.setter
    def Timezone(self, Timezone):
        self._Timezone = Timezone

    @property
    def ZipCode(self):
        r"""<p>The zip code of the IP address</p>
        :rtype: str
        """
        return self._ZipCode

    @ZipCode.setter
    def ZipCode(self, ZipCode):
        self._ZipCode = ZipCode


    def _deserialize(self, params):
        self._Country = params.get("Country")
        self._Region = params.get("Region")
        self._City = params.get("City")
        self._District = params.get("District")
        self._Longitude = params.get("Longitude")
        self._Latitude = params.get("Latitude")
        self._Timezone = params.get("Timezone")
        self._ZipCode = params.get("ZipCode")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class IPNetwork(AbstractModel):
    r"""The basic IP network information

    """

    def __init__(self):
        r"""
        :param _ISP: <p>Internet service provider</p>
        :type ISP: str
        :param _ASN: <p>Autonomous system number</p>
        :type ASN: str
        :param _Organization: <p>IP registration organization name</p>
        :type Organization: str
        :param _IsReserved: <p>Whether it is a reserved IP address</p>
        :type IsReserved: bool
        :param _IsGateway: <p>Whether it is a gateway IP address</p>
        :type IsGateway: bool
        :param _IsAnycast: <p>Whether it belongs to an anycast network</p>
        :type IsAnycast: bool
        :param _IsMobile: <p>Whether it is from a mobile network</p>
        :type IsMobile: bool
        :param _IsDynamic: <p>Whether it is a dynamic IP address</p>
        :type IsDynamic: bool
        :param _IsEgress: <p>Whether it is a network egress</p>
        :type IsEgress: bool
        :param _IsDNS: <p>Whether it is used for domain name resolution</p>
        :type IsDNS: bool
        :param _IsEducation: <p>Whether it is an educational institution</p>
        :type IsEducation: bool
        :param _IsInstitution: <p>Whether it is an organization</p>
        :type IsInstitution: bool
        :param _IsCompany: <p>Whether it is an enterprise dedicated line</p>
        :type IsCompany: bool
        :param _IsResidence: <p>Whether it is a residence broadband connection</p>
        :type IsResidence: bool
        :param _IsCloudService: <p>Whether it is cloud service</p>
        :type IsCloudService: bool
        :param _IsInfrastructure: <p>Whether it is infrastructure</p>
        :type IsInfrastructure: bool
        :param _IsMXServer: <p>Whether it is an mail exchange service</p>
        :type IsMXServer: bool
        """
        self._ISP = None
        self._ASN = None
        self._Organization = None
        self._IsReserved = None
        self._IsGateway = None
        self._IsAnycast = None
        self._IsMobile = None
        self._IsDynamic = None
        self._IsEgress = None
        self._IsDNS = None
        self._IsEducation = None
        self._IsInstitution = None
        self._IsCompany = None
        self._IsResidence = None
        self._IsCloudService = None
        self._IsInfrastructure = None
        self._IsMXServer = None

    @property
    def ISP(self):
        r"""<p>Internet service provider</p>
        :rtype: str
        """
        return self._ISP

    @ISP.setter
    def ISP(self, ISP):
        self._ISP = ISP

    @property
    def ASN(self):
        r"""<p>Autonomous system number</p>
        :rtype: str
        """
        return self._ASN

    @ASN.setter
    def ASN(self, ASN):
        self._ASN = ASN

    @property
    def Organization(self):
        r"""<p>IP registration organization name</p>
        :rtype: str
        """
        return self._Organization

    @Organization.setter
    def Organization(self, Organization):
        self._Organization = Organization

    @property
    def IsReserved(self):
        r"""<p>Whether it is a reserved IP address</p>
        :rtype: bool
        """
        return self._IsReserved

    @IsReserved.setter
    def IsReserved(self, IsReserved):
        self._IsReserved = IsReserved

    @property
    def IsGateway(self):
        r"""<p>Whether it is a gateway IP address</p>
        :rtype: bool
        """
        return self._IsGateway

    @IsGateway.setter
    def IsGateway(self, IsGateway):
        self._IsGateway = IsGateway

    @property
    def IsAnycast(self):
        r"""<p>Whether it belongs to an anycast network</p>
        :rtype: bool
        """
        return self._IsAnycast

    @IsAnycast.setter
    def IsAnycast(self, IsAnycast):
        self._IsAnycast = IsAnycast

    @property
    def IsMobile(self):
        r"""<p>Whether it is from a mobile network</p>
        :rtype: bool
        """
        return self._IsMobile

    @IsMobile.setter
    def IsMobile(self, IsMobile):
        self._IsMobile = IsMobile

    @property
    def IsDynamic(self):
        r"""<p>Whether it is a dynamic IP address</p>
        :rtype: bool
        """
        return self._IsDynamic

    @IsDynamic.setter
    def IsDynamic(self, IsDynamic):
        self._IsDynamic = IsDynamic

    @property
    def IsEgress(self):
        r"""<p>Whether it is a network egress</p>
        :rtype: bool
        """
        return self._IsEgress

    @IsEgress.setter
    def IsEgress(self, IsEgress):
        self._IsEgress = IsEgress

    @property
    def IsDNS(self):
        r"""<p>Whether it is used for domain name resolution</p>
        :rtype: bool
        """
        return self._IsDNS

    @IsDNS.setter
    def IsDNS(self, IsDNS):
        self._IsDNS = IsDNS

    @property
    def IsEducation(self):
        r"""<p>Whether it is an educational institution</p>
        :rtype: bool
        """
        return self._IsEducation

    @IsEducation.setter
    def IsEducation(self, IsEducation):
        self._IsEducation = IsEducation

    @property
    def IsInstitution(self):
        r"""<p>Whether it is an organization</p>
        :rtype: bool
        """
        return self._IsInstitution

    @IsInstitution.setter
    def IsInstitution(self, IsInstitution):
        self._IsInstitution = IsInstitution

    @property
    def IsCompany(self):
        r"""<p>Whether it is an enterprise dedicated line</p>
        :rtype: bool
        """
        return self._IsCompany

    @IsCompany.setter
    def IsCompany(self, IsCompany):
        self._IsCompany = IsCompany

    @property
    def IsResidence(self):
        r"""<p>Whether it is a residence broadband connection</p>
        :rtype: bool
        """
        return self._IsResidence

    @IsResidence.setter
    def IsResidence(self, IsResidence):
        self._IsResidence = IsResidence

    @property
    def IsCloudService(self):
        r"""<p>Whether it is cloud service</p>
        :rtype: bool
        """
        return self._IsCloudService

    @IsCloudService.setter
    def IsCloudService(self, IsCloudService):
        self._IsCloudService = IsCloudService

    @property
    def IsInfrastructure(self):
        r"""<p>Whether it is infrastructure</p>
        :rtype: bool
        """
        return self._IsInfrastructure

    @IsInfrastructure.setter
    def IsInfrastructure(self, IsInfrastructure):
        self._IsInfrastructure = IsInfrastructure

    @property
    def IsMXServer(self):
        r"""<p>Whether it is an mail exchange service</p>
        :rtype: bool
        """
        return self._IsMXServer

    @IsMXServer.setter
    def IsMXServer(self, IsMXServer):
        self._IsMXServer = IsMXServer


    def _deserialize(self, params):
        self._ISP = params.get("ISP")
        self._ASN = params.get("ASN")
        self._Organization = params.get("Organization")
        self._IsReserved = params.get("IsReserved")
        self._IsGateway = params.get("IsGateway")
        self._IsAnycast = params.get("IsAnycast")
        self._IsMobile = params.get("IsMobile")
        self._IsDynamic = params.get("IsDynamic")
        self._IsEgress = params.get("IsEgress")
        self._IsDNS = params.get("IsDNS")
        self._IsEducation = params.get("IsEducation")
        self._IsInstitution = params.get("IsInstitution")
        self._IsCompany = params.get("IsCompany")
        self._IsResidence = params.get("IsResidence")
        self._IsCloudService = params.get("IsCloudService")
        self._IsInfrastructure = params.get("IsInfrastructure")
        self._IsMXServer = params.get("IsMXServer")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        


class RiskLabel(AbstractModel):
    r"""Risk label

    """

    def __init__(self):
        r"""
        :param _Id: <p>The ID of the label</p>
        :type Id: str
        :param _Reason: <p>The reason of the label</p>
        :type Reason: str
        """
        self._Id = None
        self._Reason = None

    @property
    def Id(self):
        r"""<p>The ID of the label</p>
        :rtype: str
        """
        return self._Id

    @Id.setter
    def Id(self, Id):
        self._Id = Id

    @property
    def Reason(self):
        r"""<p>The reason of the label</p>
        :rtype: str
        """
        return self._Reason

    @Reason.setter
    def Reason(self, Reason):
        self._Reason = Reason


    def _deserialize(self, params):
        self._Id = params.get("Id")
        self._Reason = params.get("Reason")
        memeber_set = set(params.keys())
        for name, value in vars(self).items():
            property_name = name[1:]
            if property_name in memeber_set:
                memeber_set.remove(property_name)
        if len(memeber_set) > 0:
            warnings.warn("%s fileds are useless." % ",".join(memeber_set))
        